### ISSUE TITLE
Python GUI crashes on any action

### ISSUE THREAD

**Issue by j2kun** [FrameworkComputer/qmk_hid#33]
E.g.

```
Traceback (most recent call last):
  File "/home/jeremy/macropad/python/qmk_hid/gui.py", line 739, in <module>
    main()
  File "/home/jeremy/macropad/python/qmk_hid/gui.py", line 325, in main
    set_rgb_u8(dev, RGB_MATRIX_VALUE_EFFECT, effect)
  File "/home/jeremy/macropad/python/qmk_hid/gui.py", line 559, in set_rgb_u8
    send_message(dev, CUSTOM_SET_VALUE, msg, 0)
  File "/home/jeremy/macropad/python/qmk_hid/gui.py", line 547, in send_message
    debug_print("Error: ", ex)
TypeError: debug_print() takes from 0 to 1 positional arguments but 2 were given

```

**Comment by JohnAZoidberg** [comment]
Should be fixed by #36
